# database access
database_name: "test"
dynamo_region: "http://127.0.0.1:4567"
dynamo_access_key: "access"
dynamo_secret_key: "secret"

# table dessription
tables:
    -
        name: "users"
        attributes:
            - { name: "id", type: "N", required: true }
            - { name: "first_name", type: "S", required: false }
            - { name: "last_name", type: "S", required: false }
            - { name: "email", type: "S", required: true }
            - { name: "country", type: "S", required: false }
        primary_key:
            type: "HASH"
            hash: "id"
        secondary_indexes:
            - { name: "email", type: "HASH", hash: "email" }
    -
        name: "game_scores"
        attributes:
            - { name: "user_id", type: "N", required: true }
            - { name: "game_title", type: "S", required: true }
            - { name: "top_score", type: "N", required: false }
            - { name: "wins", type: "N", required: true }
            - { name: "losts", type: "N", required: true }
        primary_key:
            type: "RANGE"
            hash: "game_title"
            range: "user_id"
        secondary_indexes:
            - { name: "wins_losts", type: "RANGE", hash: "wins", range: "losts" }
    -
        name: "restaurants"
        attributes:
            - { name: "id", type: "N", required: true }
            - { name: "name", type: "S", required: true }
            - { name: "lat", type: "N", required: true }
            - { name: "long", type: "N", required: true }
            - { name: "description", type: "S", required: false }
        primary_key:
            type: "HASH"
            hash: "id"
